### ISSUE TITLE
Compile errors on Raspberry Pi

### ISSUE THREAD

**Issue by jsavage** [espruino/EspruinoWebIDE#161]
The following errors encountered when compiling this on Raspberry pi when following [this tutorial](https://www.espruino.com/Raspberry+Pi+Web+IDE).  I am not sure which if any of these are significant or how to resolve / troubleshoot but given the suggestion in the tutorial that some errors may arise it might be helpful to try and indicate in the tutorial (or in the make file somehow) which are significant and which are expected and can be ignored. 

```
sudo npm install -g espruino-web-ide
/usr/bin/espruino-web-ide -> /usr/lib/node_modules/espruino-web-ide/nw-loader.js
/usr/bin/espruino-server -> /usr/lib/node_modules/espruino-web-ide/server.js

> winnus@0.0.2 install /usr/lib/node_modules/espruino-web-ide/node_modules/winnus
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/7.3.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/espruino-web-ide/node_modules/winnus/.node-gyp"
make: Entering directory '/usr/lib/node_modules/espruino-web-ide/node_modules/winnus/build'
  CXX(target) Release/obj.target/winnus/cpp/winnus.o
../cpp/winnus.cpp:3:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning (disable: 4068)
 ^
../cpp/winnus.cpp:10:21: fatal error: windows.h: No such file or directory
 #include <windows.h>
                     ^
compilation terminated.
winnus.target.mk:90: recipe for target 'Release/obj.target/winnus/cpp/winnus.o' failed
make: *** [Release/obj.target/winnus/cpp/winnus.o] Error 1
make: Leaving directory '/usr/lib/node_modules/espruino-web-ide/node_modules/winnus/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.34-v7+
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/espruino-web-ide/node_modules/winnus
gyp ERR! node -v v7.3.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
/usr/lib
└─┬ espruino-web-ide@0.65.11 
  ├─┬ serialport@4.0.7
  │ ├── debug@2.5.1 
  │ └── nan@2.5.0 
  └── utf8@2.1.2 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@~0.1.4 (node_modules/espruino-web-ide/node_modules/noble/node_modules/xpc-connection):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for xpc-connection@0.1.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: winnus@0.0.2 (node_modules/espruino-web-ide/node_modules/winnus):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: winnus@0.0.2 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```
```
pi@raspberrypi7:~ $ uname -a
Linux raspberrypi7 4.4.34-v7+ #930 SMP Wed Nov 23 15:20:41 GMT 2016 armv7l GNU/Linux

```

**Comment by gfwilliams** [comment]
Does it still work afterwards? As far as I can tell it's complaining about `winnus` - which is an optional thing that's only needed on Windows 10. I think it should still work fine without that

**Comment by gfwilliams** [comment]
Hi John.

Did you have a chance to check this out? Did it actually work?

Even if nw.js won't install on the Pi, you should still be able to run `server.js` which will allow you connect via `localhost:8080` and a normal web browser
