### ISSUE TITLE
Get "Error: Cannot find module 'nw/bin/nw'" when running Espruino Web IDE

### ISSUE THREAD

**Issue by psiphi75** [espruino/EspruinoWebIDE#175]
I have installed Espruino Web IDE on Linux (Ubuntu 17.04) using the following command:

```sh
sudo npm install -g espruino-web-ide
```

However, when I run `espruino-web-ide` I get the following error:

```
module.js:327
    throw err;
    ^

Error: Cannot find module 'nw/bin/nw'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.require.resolve (internal/module.js:16:19)
    at Object.<anonymous> (/usr/lib/node_modules/espruino-web-ide/nw-loader.js:6:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3
```

node v4.8.2
npm v2.15.11
espruino-web-ide v0.65.11

**Comment by gfwilliams** [comment]
Thanks - have you tried `npm install -g nw` or installing straight from https://nwjs.io/?

It doesn't come as a dependency because it's reasonably common just to want to run `espruino-server` on something like a Pi - in which case you don't want to install the (relatively large) NW.js and all its dependencies

**Comment by psiphi75** [comment]
Thanks, that resolves it, I have updated the instructions and have a Pull Request that closes this issue.

**Comment by gfwilliams** [comment]
Great - thanks!
