### ISSUE TITLE
Esprima Minification -- TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by dweremeichik** [espruino/EspruinoWebIDE#190]
When using Esprima minification I seem to be getting the following error:
```
ERROR: [notify_error] TypeError: Cannot read property 'length' of undefined
ERROR: TypeError: Cannot read property 'length' of undefined     at Object.traverse (chrome-extension://bleoifhkdalbjfbobjackfdifdneehpo/main.js:91184:42)     at annotateDirective (chrome-extension://bleoifhkdalbjfbobjackfdifdneehpo/main.js:92040:16)     at Object.optimize (chrome-extension://bleoifhkdalbjfbobjackfdifdneehpo/main.js:90208:16)     at obfuscate (chrome-extension://bleoifhkdalbjfbobjackfdifdneehpo/main.js:99711:27)     at minifyCodeEsprima (chrome-extension://bleoifhkdalbjfbobjackfdifdneehpo/main.js:99692:18)     at minify (chrome-extension://bleoifhkdalbjfbobjackfdifdneehpo/main.js:99837:23)     at Array.<anonymous> (chrome-extension://bleoifhkdalbjfbobjackfdifdneehpo/main.js:99666:7)     at cb (chrome-extension://bleoifhkdalbjfbobjackfdifdneehpo/main.js:78196:15)     at findASMBlocks (chrome-extension://bleoifhkdalbjfbobjackfdifdneehpo/main.js:84982:5)     at Array.<anonymous> (chrome-extension://bleoifhkdalbjfbobjackfdifdneehpo/main.js:84888:7)
```

It only seems to break when I have a specific module included, however this issue is not present when using no minification, or closure - whitespace only.

For completeness, the (WIP) module is:
```js
function Menu (display, buttons, map) {
    if (!buttons || buttons.length < 4 ) throw new Error('You must supply 4 control buttons.');
    if (!map || !map.root) throw new Error('A map with a minimum of a "root" object must be supplied');
    this.display = display;
    this.buttons = {
      back: buttons[0],
      up: buttons[1],
      down: buttons[2],
      select: buttons[3]
    };
    this.menu = map;
    this.currentSub = 'root';
    this.subPointer = 0;
    this.subStack = [];
    this.page = null;
    this.width = 18;
    this.height = 2;
    this.characters = {
      arrow_right: 0b01111110
    };
  
    // Down
    pinMode(this.buttons.down,'input_pulldown');
    setWatch(() => {
      this.updateMenu(this.subPointer + 1);
    }, this.buttons.down, { repeat: true, edge: 'rising', debounce: 25 });
  
    // Up
    pinMode(this.buttons.up,'input_pulldown');
    setWatch(() => {
      this.updateMenu(this.subPointer - 1);
    }, this.buttons.up, { repeat: true, edge: 'rising', debounce: 25 });
  
    // Select
    pinMode(this.buttons.select,'input_pulldown');
    setWatch(() => {
      let currentItem = this.menu[this.currentSub].items[this.subPointer];
        let actionPromise = new Promise((resolve, reject) => {
          if (currentItem.action) {
            currentItem.action().then((result) => {
              console.log(result); 
            }).catch((err) => {
              console.log('listError', err); 
            });
          } else {
            resolve();
          }
        });
        actionPromise.then(() => {
          if (currentItem.menu) {
            this.subStack.push(this.currentSub);
            this.currentSub = currentItem.menu;
            this.page = null;
            this.subPointer = null;
            this.updateMenu(0);
          }
        });
    }, this.buttons.select, { repeat: true, edge: 'rising', debounce: 25 });
  
    // Back
    pinMode(this.buttons.back,'input_pulldown');
    setWatch(() => {
      let newSub = this.subStack.pop();
      if (newSub) {
        this.currentSub = newSub;
        this.page = null;
        this.subPointer = null;
      }
      this.updateMenu(0);
    }, this.buttons.back, { repeat: true, edge: 'rising', debounce: 25 });
  
    this.writeMenu();
  }

Menu.prototype.writeMenu = function () {
    // Find new page
    let previousItemCount = this.subPointer % this.height;
    let page = (this.subPointer - previousItemCount) / this.height;
    let items = [];
    let nextName = this.menu[this.currentSub].items[this.subPointer].name;
    // Fill in previous (and current) items
    for (let i = previousItemCount; i >= 0; i -= 1) {
     items.push(this.menu[this.currentSub].items[this.subPointer - i]); 
    }
    // Fill in next items
    if (items.length < this.height && this.menu[this.currentSub].items) {
      for (let i = items.length; i < this.height && this.subPointer + i < this.menu[this.currentSub].items.length; i += 1) {
       items.push(this.menu[this.currentSub].items[this.subPointer + i]); 
      }
    }
    // Clear display
    if ( page !== this.page){
      this.display.clear();
    }
    // Write the menu
    for (let i = 0; i < items.length; i += 1) {
      this.display.setCursor(0, i);
      if (items[i].name === nextName) {
        this.display.write(this.characters.arrow_right);
      } else {
        this.display.print(' ');
      }
      if (page !== this.page) {
        this.display.print(items[i].name);
      }
    }
    // Set new page
    this.page = page;
  };
  
  Menu.prototype.updateMenu = function (newPointer) {
    // Ensure we are within bounds.
     let itemSet = this.menu[this.currentSub].items || [];
     if (newPointer >= itemSet.length) {
      newPointer = itemSet.length - 1;
     } else if (newPointer < 0) {
      newPointer = 0; 
     }
  
     // Update if changes made.
     if (newPointer !== this.subPointer) {
       console.log('writing menu');
       this.subPointer = newPointer;
       this.writeMenu();
     }
  };

  exports = Menu;
```

**Comment by dweremeichik** [comment]
Would [Babel Standalone](https://github.com/babel/babel/tree/master/packages/babel-standalone) 1.8M (for transpiling) combined with [Babili Standalone](https://github.com/babel/babel-standalone/tree/master/packages/babili-standalone) 64K (for minifying) be any better?

I'm not sure what ES spec version (if any) Espruino is built to, however it seems like it could benefit from having a solid transpilier as a default option.

Disclaimer: I haven't used the standalone version of Babel, nor have I used Babili at all.

**Comment by gfwilliams** [comment]
This is now fixed just by using a newer version of Esprima.

There's also Rollup that's been added and which might be useful for transpiling, but it doesn't currently work in the chrome web app so I probably won't actually be able to release it it.
