### ISSUE TITLE
Debian buster optional dependencies installation fails

### ISSUE THREAD

**Issue by enthusiasmus** [espruino/EspruinoWebIDE#229]
During npm install I receive following error:

```
make: *** [binding.target.mk:111: Release/obj.target/binding/src/BluetoothHciSocket.o] Fehler 1
make: Verzeichnis „/home/lukas/projects/EspruinoWebIDE/node_modules/bluetooth-hci-socket/build“ wird verlassen
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/lukas/npm-global/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.19.0-5-amd64
gyp ERR! command "/usr/bin/node" "/home/lukas/npm-global/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/lukas/projects/EspruinoWebIDE/node_modules/bluetooth-hci-socket
gyp ERR! node -v v12.16.2
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
```
OS: 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5+deb10u2 (2019-08-08) x86_64 GNU/Linux

I had to fork the dependency `noble` and change the `bluetooth-hci-socket` packet to the newer one https://github.com/abandonware/node-bluetooth-hci-socket 

No I reference my own `noble` fork and now it works for me!

Best regards,
Lukas

**Comment by gfwilliams** [comment]
Thanks! Just updated it to directly reference the abandonware noble
